### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by hakilebara** [jschilli/ember-cli-file-creator#7]
```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-file-creator`
    at Function.Addon.lookup ([redacted]/ember/node_modules/ember-cli/lib/models/addon.js:1006:27)```

I think the init() function in index.js should include `this._super.init && this._super.init.apply(this, arguments);`

```
ember            : 2.7.0
ember-cli        : 2.8.0-beta.2
```

**Comment by jschilli** [comment]
closed via #8
